server:
  port: 10010

spring:
  profiles:
    active: @profiles.active@
  jackson:
    serialization:
      write-dates-as-timestamps: true


logging:
  config: classpath:log4j2.xml



#spring:
#  cloud:
#    sentinel:
#      #心跳启动
#      eager: true
#      transport:
#        #sentinel控制台访问路径
#        dashboard: 127.0.0.1:8080
#        port: 8080
#      datasource:
#        ds:
#          nacos:
#            #读取哪个命名空间的配置(要和上面的nacos.config.namespace配置一致，否则会读不到文件。如果默认public，则可以不写)
#            namespace: b417a5f2-5e80-486b-bd2f-8a585ca3e82f
#            server-addr: 101.43.126.26:8848
#            #限流规则配置文件的名称
#            dataId: springboot-sentinel-gateway.json
#            groupId: springboot-gateway
#            data-type: json
#            rule-type: flow
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      default-filters:
#        - name: IpBlackListFilter
#          args:
#            blackIpList:
#              - 101.43.126.26
#      routes:
#        - id: springboot-nacos
#          uri: lb://springboot-nacos-service
#          predicates:
#            - Path=/nacos/**
#          filters:
#            - StripPrefix=1
#        - id: springboot-sentinel
#          uri: lb://springboot-sentinel-service
#          predicates:
#            - Path=/sentinel/**
#          filters:
#            - StripPrefix=1
#        - id: springboot-uaa
#          uri: lb://springboot-uaa-service
#          predicates:
#            - Path=/uaa/**
#          filters:
#            - StripPrefix=1
#
#gateway:
#  security:
#    http-urls:
#      - /uaa/auth/login

#
#  [
#    {
#      "resource":"springboot-uaa",
#      "limitApp":"default",
#      "grade":1,
#      "count":1,
#      "strategy":0,
#      "controlBehavior":0,
#      "clusterMode":"false"
#    }
#  ]



